package commands

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
	"github.com/JNZader/ai-toolkit/goreview/internal/config"
)

var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Initialize GoReview in the current project",
	Long: `Sets up GoReview in the current directory.
1. Creates a default .goreview.yaml configuration file.
2. Installs a git pre-commit hook to run reviews automatically.`, 
	RunE: runInit,
}

func init() {
	rootCmd.AddCommand(initCmd)
}

func runInit(cmd *cobra.Command, args []string) error {
	cwd, err := os.Getwd()
	if err != nil {
		return err
	}

	fmt.Printf("🚀 Initializing GoReview in %s\n", cwd)

	// 1. Crear Config
	if err := createConfigFile(cwd); err != nil {
		return err
	}

	// 2. Instalar Git Hook
	if err := installGitHook(cwd); err != nil {
		fmt.Printf("⚠️  Could not install git hook: %v\n", err)
	}

	fmt.Println("\n✅ GoReview initialized successfully!")
	fmt.Println("Try running: goreview review --staged")
	return nil
}

func createConfigFile(cwd string) error {
	configPath := filepath.Join(cwd, ".goreview.yaml")
	if _, err := os.Stat(configPath); err == nil {
		fmt.Println("ℹ️  .goreview.yaml already exists, skipping.")
		return nil
	}

	cfg := config.DefaultConfig()
	data, err := yaml.Marshal(cfg)
	if err != nil {
		return fmt.Errorf("failed to marshal default config: %w", err)
	}

	// Agregar comentarios explicativos al YAML generado (opcional, pero útil)
	header := []byte("# GoReview Configuration\n# Generated by goreview init\n\n")
	data = append(header, data...)

	if err := os.WriteFile(configPath, data, 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	fmt.Println("✅ Created .goreview.yaml")
	return nil
}

func installGitHook(cwd string) error {
	gitDir := filepath.Join(cwd, ".git")
	if _, err := os.Stat(gitDir); os.IsNotExist(err) {
		return fmt.Errorf("not a git repository (run 'git init' first)")
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	if err := os.MkdirAll(hooksDir, 0755); err != nil {
		return err
	}

	hookPath := filepath.Join(hooksDir, "pre-commit")
	
	// Script del hook
	hookContent := `#!/bin/sh
# GoReview Pre-commit Hook
# Generated by goreview init

# Check if goreview is installed
if ! command -v goreview >/dev/null 2>&1; then
    echo "⚠️  GoReview not found in PATH. Skipping review."
    exit 0
fi

echo "🔍 GoReview: Analyzing staged changes..."

# Run review on staged files
# If issues are found, goreview returns exit code 1, stopping the commit.
goreview review --staged

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo ""
    echo "❌ GoReview found issues."
    echo "   Use 'git commit --no-verify' to bypass if necessary."
    exit 1
fi

exit 0
`

	if err := os.WriteFile(hookPath, []byte(hookContent), 0755); err != nil {
		return fmt.Errorf("failed to write hook file: %w", err)
	}

	// Asegurar permisos de ejecución (importante para Linux/Mac/WSL)
	if err := os.Chmod(hookPath, 0755); err != nil {
		return fmt.Errorf("failed to make hook executable: %w", err)
	}

	fmt.Println("✅ Installed .git/hooks/pre-commit")
	return nil
}
