import { Octokit } from '@octokit/rest';
import { logger } from '../logger.js';
import { config } from '../config.js';
import axios from 'axios';

export class DocsService {
  
  async handlePush(
    octokit: Octokit,
    owner: string,
    repo: string,
    ref: string,
    commits: any[]
  ) {
    // Evitar bucles: Si el ultimo commit es del bot, ignorar
    const lastCommit = commits[0];
    if (lastCommit && lastCommit.author.name === 'goreview-bot') {
      logger.info('Ignoring push from bot');
      return;
    }

    try {
      logger.info({ owner, repo, ref }, 'Analyzing push for documentation updates');

      // 1. Obtener README actual
      let currentReadme = '';
      let sha = '';
      try {
        const { data } = await octokit.repos.getContent({
          owner,
          repo,
          path: 'README.md',
        });
        
        if ('content' in data && 'sha' in data) {
          currentReadme = Buffer.from(data.content, 'base64').toString('utf-8');
          sha = data.sha;
        }
      } catch (e) {
        logger.warn('README.md not found, creating new');
      }

      // 2. Obtener Diff del push (comparado con el commit anterior)
      const after = commits[0].id;
      
      const { data: compare } = await octokit.repos.compareCommits({
        owner, repo, base: `${after}~1`, head: after // Compare last commit
      });

      // No changes?
      if (!compare.files || compare.files.length === 0) return;

      // 3. Generar nueva documentacion usando Ollama (Direct API call here for simplicity, or via goreview CLI)
      // Usaremos llamada directa a Ollama para flexibilidad
      const prompt = `
You are a documentation maintainer. Update the following README based on the code changes.
Keep the existing structure. Only add/modify relevant sections.

OLD README:
${currentReadme}

CODE CHANGES (Diff):
${JSON.stringify(compare.files.map(f => f.patch).join('\n').substring(0, 5000))}

OUTPUT (Full Markdown):
`;

      const aiResponse = await this.callOllama(prompt);
      if (!aiResponse) return;

      // 4. Crear PR con la actualizacion
      // Check if branch exists
      const branchName = `docs/update-${Date.now()}`;
      
      // Get ref sha
      const { data: refData } = await octokit.git.getRef({ owner, repo, ref: ref.replace('refs/', '') });
      
      // Create branch
      await octokit.git.createRef({
        owner, repo, ref: `refs/heads/${branchName}`, sha: refData.object.sha
      });

      // Update file
      await octokit.repos.createOrUpdateFileContents({
        owner, repo, path: 'README.md',
        message: 'docs: auto-update README based on recent changes',
        content: Buffer.from(aiResponse).toString('base64'),
        sha: sha || undefined,
        branch: branchName
      });

      // Create PR
      await octokit.pulls.create({
        owner, repo,
        title: 'docs: Update README',
        body: 'Automatic documentation update generated by GoReview AI.',
        head: branchName,
        base: ref.replace('refs/heads/', '')
      });

      logger.info('Documentation PR created');

    } catch (error) {
      logger.error({ error }, 'Failed to update docs');
    }
  }

  private async callOllama(prompt: string): Promise<string> {
    try {
      const res = await axios.post(`${config.OLLAMA_HOST}/api/generate`, {
        model: config.OLLAMA_MODEL,
        prompt: prompt,
        stream: false
      });
      return res.data.response;
    } catch (e) {
      logger.error(e, 'Ollama call failed');
      return '';
    }
  }
}

export const docsService = new DocsService();
