package report

import (
	"fmt"
	"io"
	"strings"
	"text/template"
	"time"

	"github.com/JNZader/ai-toolkit/goreview/internal/review"
)

// MarkdownReporter genera reportes en formato Markdown
type MarkdownReporter struct{}

const markdownTemplate = `# GoReview Report

**Date:** {{ .Date }}
**Duration:** {{ .Duration }}
**Total Issues:** {{ .TotalIssues }}

## Summary

{{ .Summary }}

## Files Analyzed

{{ range .Files }}
### 📄 {{ .File }}

{{ if .Error }}
❌ **Error:** {{ .Error }}
{{ else }}
**Issues:** {{ len .Response.Issues }} {{ if .Cached }}(Cached){{ end }}

{{ range .Response.Issues }}
#### [{{ .Severity | ToUpper }}] {{ .Type }}
> {{ .Message }}

**Suggestion:**
{{ .Suggestion }}

{{ if .Location }}
*Location: Line {{ .Location.StartLine }}*
{{ end }}

---
{{ end }}
{{ end }}
{{ end }}

Generated by [GoReview](https://github.com/JNZader/ai-toolkit)
`

// Generate genera el reporte markdown
func (r *MarkdownReporter) Generate(result *review.Result, w io.Writer) error {
	tmpl, err := template.New("markdown").Funcs(template.FuncMap{
		"ToUpper": strings.ToUpper,
	}).Parse(markdownTemplate)
	if err != nil {
		return fmt.Errorf("failed to parse template: %w", err)
	}

	data := struct {
		Date        string
		Duration    time.Duration
		TotalIssues int
		Summary     string
		Files       []review.FileResult
	}{
		Date:        time.Now().Format(time.RFC1123),
		Duration:    result.Duration,
		TotalIssues: result.TotalIssues,
		Summary:     result.Summary,
		Files:       result.Files,
	}

	if data.Summary == "" {
		data.Summary = fmt.Sprintf("Analysis completed successfully. %d files processed.", len(result.Files))
	}

	return tmpl.Execute(w, data)
}
